services:
  blog:
    build: .
    platform: linux/amd64
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling
